dist: xenial
language: perl
jobs:
  include:
  - perl: "5.8"
    dist: trusty
  - perl: "5.28"
before_install:
- export PERL_CPANM_OPT='--no-interactive --no-man-pages --notest --skip-satisfied'
install:
- cpanm IPC::System::Simple
- cpanm Perl::Critic
script:
- make
- shellcheck git-wshow
- make test

# vim:ts=2 sts=2 sw=2 et
