#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

usage()
{
    printf 'Usage:\n  %s [-r REMOTE] COMMIT\n' "$prog"
}

set -e -u -C
prog="${0##*/}"
remote=origin
while getopts 'hr:' opt
do
    case "$opt" in
        h) usage; exit 0;;
        r) remote="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
[ $# -gt 0 ] || set -- HEAD
if [ $# -ne 1 ]
then
    usage >&2
    exit 1
fi
commit=$(git rev-parse "$@")
remote_url=$(git remote get-url "$remote")
url=
case $remote_url in
    https://github.com/*|https://gitlab.com/*|https://salsa.debian.org/*|https://gitlab.gnome.org/*)
        url="${remote_url%.git}/commit/$commit";;
    https://anongit.freedesktop.org/git/*)
        repo=${remote_url#https://anongit.freedesktop.org/git/}
        url="https://cgit.freedesktop.org/${repo%.git}/commit/?id=$commit";;
    https://git.savannah.gnu.org/git/*)
        repo=${remote_url#https://git.savannah.gnu.org/git/}
        url="https://git.savannah.gnu.org/cgit/${repo%.git}.git/commit/?id=$commit";;
    https://git.savannah.nongnu.org/git/*)
        repo=${remote_url#https://git.savannah.nongnu.org/git/}
        url="https://git.savannah.nongnu.org/cgit/${repo%.git}.git/commit/?id=$commit";;
    git://git.code.sf.net/p/*|https://git.code.sf.net/p/*)
        repo=${remote_url#*://git.code.sf.net/p/}
        url="https://sourceforge.net/p/${repo%.git}/ci/$commit/";;
esac
if [ -z "$url" ]
then
    printf '%s: unsupported remote URL %s\n' "$prog" "$remote_url"
    exit 1
fi
for browser in sensible-browser xdg-open
do
    command -v "$browser" > /dev/null && break
done
exec "$browser" "$url"

# vim:ts=4 sts=4 sw=4 et
