#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

strip()
{
    v="$1"
    while true
    do
        case $v in
            ' '*)
                v="${v#[ ]}";;
            *' ')
                v="${v%[ ]}";;
            *)
                printf '%s' "$v"
                break;;
        esac
    done
}

printf 'case $remote_url in\n'
for file in "$@"
do
    while read line
    do
        case $line in
            '#'*);;
            '['*']') group="$line";;
            *=*)
                if [ "$group" = '[rules]' ]
                then
                    src=$(strip "${line%%=*}")
                    dst=$(strip "${line#*=}")
                    printf '    %s)\n' "$src"
                    case "$src" in
                        *'*')
                            printf '        repo=${remote_url#%s}\n' "${src%'*'}"
                    esac
                    printf '        url="%s";;\n' "$dst"
                fi;;
        esac
    done < "$file"
done
printf 'esac\n'

# vim:ts=4 sts=4 sw=4 et
