name: CI
on:
- push
- pull_request
permissions: {}
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run:
        sudo apt-get install libipc-system-simple-perl
    - name: build
      run:
        make
    - name: run shellcheck
      run:
        shellcheck git-wshow
    - name: run tests
      run:
        make test
    - name: make install
      run:
        make install PREFIX=~/.local
    - name: make clean
      run:
        make clean
    - name: post-install smoke test
      run: |
        BROWSER=echo git wshow
    - name: check README syntax
      run: |
        pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README
  network:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test IPv4 connectivity
      run:
        curl -sv4 http://example.org > /dev/null
    - name: test IPv6 connectivity
      run:
        curl -sv6 http://example.org > /dev/null
      continue-on-error: true
    - name: extract URLs
      run: |
        args=(
          -e '/icube-forge.unistra.fr/'  # network error
          -e '/jff.email/'  # IPv4 misconfiguration <20231023201111.gosefghj357uie6x@jwilk.net>
          -e '/git.gavinhoward.com/'  # HTTP 403
          -e '/git.sesse.net/'  # https://blog.sesse.net/blog/tech/2024-12-31-09-48_git_sesse_net_goes_ipv6_only
          -e '/git.sr.ht/'  # HTTP 403
          -e '/cgit.freedesktop.org/'  # timeout
          -e '/git.busybox.net/'  # timeout
          -e '/git.gnu.org.ua/'  # HTTP 429
          -e '/git.musl-libc.org/'  # timeout
          -e '/git.openwrt.org/'  # timeout
          -e '/git.pengutronix.de/'  # timeout
          -e '/git.sigxcpu.org/'  # HTTP 502
          -e '/notabug.org/'  # HTTP 502
          # URLs ill-supported by lychee <https://github.com/lycheeverse/lychee/issues/1872>:
          -e '/android.googlesource.com/'
          # these are broken also outside CI env:
          -e '/review.coreboot.org/'  # HTTP 404
          -e '/git.seabios.org/'  # HTTP 404
          -e '/gerrit.ovirt.org/'  # HTTP 502
          -e '/keithp.com/'  # HTTP 404, connection errors
          -e '/git.skoll.ca/'  # HTTP 401
          -e '/git.guilhem.org/'  # timeout
          -e '/aur.archlinux.org/'  # HTTP 502
          -e '/bues.ch/'  # HTTP 403 without Referer
          -e '/cgit.adelielinux.org/'  # timeout or HTTP 503
          -e '/cgit.ghostscript.com/'  # HTTP 401
          -e '/code.opensuse.org/'  # HTTP 403
          -e '/evolvis.org/'  # timeout or HTTP 401
          -e '/ezix.org/'  # HTTP 403
          -e '/git.breakpoint.cc/'  # HTTP 502
          -e '/git.eyrie.org/'  # HTTP 403
          -e '/git.joeyh.name/'  # HTTP 503
          -e '/git.kraxel.org/'  # timeout
          -e '/git.lighttpd.net/'  # HTTP 402
          -e '/git.marlam.de/'  # HTTP 403
          -e '/git.remlab.net/'  # HTTP 503
          -e '/git.unit193.net/'  # timeout
          -e '/gitlab.isc.org/'  # connection error
          -e '/ncurses.scripts.mit.edu/'  # HTTP 503
          -e '/projects.blender.org/'  # HTTP 403
          # JS-based anti-bot protection:
          -e '/git.nadeko.net/'  # HTTP 418
          -e '/git.zzls.xyz/'  # HTTP 418
        )
        grep -hoP '\bhttps://\S+\b[0-9a-f]{40,}\b\S*' data/* |
          grep -vF "${args[@]}" > lychee.urls
    - name: check URLs
      uses: lycheeverse/lychee-action@v2
      with:
        fail: true
        args: --verbose --no-progress lychee.urls

# vim:ts=2 sts=2 sw=2 et
