name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run:
        sudo apt-get install libipc-system-simple-perl
    - name: build
      run:
        make
    - name: run shellcheck
      run:
        shellcheck git-wshow
    - name: run tests
      run:
        make test
    - name: make install
      run:
        make install PREFIX=~/.local
    - name: make clean
      run:
        make clean
    - name: post-install smoke test
      run: |
        BROWSER=echo git wshow
    - name: check README syntax
      run: |
        pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README
  network:
    runs-on: ubuntu-latest
    container: lycheeverse/lychee
    steps:
    - uses: actions/checkout@v3
    - name: run tests
      run:
        grep -hoP '\bhttps://\S+\b[0-9a-f]{40,}\b\S*' data/*
        | grep -vF
          -e '/git.elephly.net/'
          -e '/git.sigxcpu.org/'
          -e '/git.webkit.org/'
          -e '/gitlab.com/'
        | NO_COLOR=1 lychee --verbose --no-progress -

# vim:ts=2 sts=2 sw=2 et
