name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run:
        sudo apt-get install libipc-run-perl
    - run:
        make
    - run:
        shellcheck git-wshow
    - run:
        make test
    - run:
        make install PREFIX=~/.local
    - run:
        make clean
    - name: post-install smoke test
      run: |
        BROWSER=echo git wshow

# vim:ts=2 sts=2 sw=2 et
